#
# validate yml:
# circleci config validate -c .circleci/config.yml
#

version: 2

#
# Defaults
#
defaults: &defaults
  docker:
    - image: naturalcycles/ci-node:latest
  working_directory: ~/repo

restore_cache: &restore_cache
  key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-v1-{{ checksum "yarn.lock" }}

save_cache: &save_cache
  paths:
    - node_modules
  key: deps-{{ .Environment.CIRCLE_PROJECT_REPONAME }}-v1-{{ checksum "yarn.lock" }}

release: &release
  name: Release (if needed)
  command: yarn release

#
# Jobs
#
jobs:
  build-job:
    <<: *defaults
    steps:
      - checkout

      # yarn
      - restore_cache: *restore_cache
      - run: yarn --pure-lockfile
      - save_cache: *save_cache

      # release
      - run: *release

  nightly-job:
    <<: *defaults
    steps:
      - checkout

      # yarn (no cache)
      - run: yarn --pure-lockfile

#
# Workflows
#
workflows:
  version: 2
  default-workflow:
    jobs:
      - build-job:
          filters:
            branches:
              only: master

  nightly-workflow:
    triggers:
      - schedule:
          cron: "0 4 * * *" # 04:00 every day
          filters:
            branches:
              only: master
    jobs:
      - nightly-job
