name: release

on:
  push:
    branches: [master, next]

jobs:
  release-job:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    env: {NODE_OPTIONS: '--max-old-space-size=3200'}
    steps:
      - { uses: actions/checkout@v2, with: { persist-credentials: true } }
      - { uses: actions/setup-node@v2, with: { node-version: 14, cache: 'yarn' } }
      - { name: yarn, run: yarn --frozen-lockfile }

      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn release
